set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'kristijanhusak/tmux-simple-git-status'
set-option -g @plugin 'b0o/tmux-autoreload'

set -g status-left "#{simple_git_status}"

set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding
set -g @vim_navigator_prefix_mapping_clear_screen ""

run '~/.tmux/plugins/tpm/tpm'

unbind C-b
set-option -g prefix M-Space
bind M-Space send-prefix

bind | split-window -h 
bind - split-window -v

unbind '"'
unbind %
